import turtle, random
width, height = turtle.window_width(), turtle.window_height()
print(width , height)

minX, maxX = -width/2, width/2
minY, maxY = -height/2, height/2
print(minX,maxX,minY,maxY)
initial_x=minX-335
initial_y=maxY-40
second_row_y=initial_y - 150
third_row_y=second_row_y - 150
fourth_row_y=third_row_y - 150
mu=25
turtle.setup(1365,710)
turtle.bgcolor("black")

colors  = ["red","green","blue","orange","purple","pink","yellow"]
def write_a():
    a = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    a.color(pen,al)
    a.speed()
    a.up()
    a.setposition(initial_x,initial_y)
    a.down()
    a.shape("turtle")
    a.left(62.56)
    a.forward(80*pow(5,0.2))
    a.right(125.12)
    a.forward(80*pow(5,0.2))
    a.up()
    a.backward((80*pow(5,0.2))/2)
    a.down()
    a.right(117.12)
    a.forward(50)
    a.hideturtle()
     
def write_b():
    b = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    b.color(pen,al)
    b.up()
    b.setposition(initial_x,initial_y)
    b.forward(180)
    b.down()
    b.shape("turtle")
    b.left(90)
    b.forward(100)
    b.right(90)
    b.forward(25)
    b.circle(-25,180)
    b.forward(25)
    b.right(180)
    b.forward(25)
    b.circle(-25,180)
    b.forward(25)
    b.hideturtle()

def write_c():
    c  = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    c.color(pen,al)
    c.up()
    c.setposition(initial_x,initial_y)
    c.forward(355+mu)
    c.down()
    c.shape("turtle")
    c.circle(50,50)
    c.up()
    c.circle(50,100)
    c.down()
    c.circle(50,210)
    c.hideturtle()

def write_d():
    d=turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    d.color(pen,al)
    d.up()
    d.setposition(initial_x,initial_y)
    d.forward(455+mu)
    d.down()
    d.shape("turtle")
    d.left(90)
    d.forward(100)
    d.right(90)
    d.forward(25)
    d.circle(-50,180)
    d.forward(25)
    d.hideturtle()
    
def write_e():
    e = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    e.color(pen,al)
    e.up()
    e.setposition(initial_x,initial_y)
    e.forward(580+2*mu)
    e.down()
    e.shape("turtle")
    e.left(90)
    e.forward(100)
    e.right(90)
    e.forward(100)
    e.right(135)
    e.up()
    e.forward(50*pow(2,0.5))
    e.down()
    e.right(45)
    e.forward(50)
    e.left(90)
    e.up()
    e.forward(50)
    e.down()
    e.left(90)
    e.forward(100)
    e.hideturtle()
    
def write_f():
    f = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    f.color(pen,al)
    f.up()
    f.setposition(initial_x,initial_y)
    f.forward(730+2*mu)
    f.down()
    f.shape("turtle")
    f.left(90)
    f.forward(100)
    f.right(90)
    f.forward(100)
    f.right(135)
    f.up()
    f.forward(50*pow(2,0.5))
    f.down()
    f.right(45)
    f.forward(50)
    f.hideturtle()
    
def write_g():
    g  = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    g.color(pen,al)
    g.up()
    g.setposition(initial_x,initial_y)
    g.forward(930+2*mu)
    g.down()
    g.shape("turtle")
    g.left(90)
    g.forward(40)
    g.right(90)
    g.forward(35)
    g.right(90)
    g.forward(40)
    g.right(90)
    g.up()
    g.forward(35)
    g.down()
    g.circle(-50,210)
    g.hideturtle()
    
def write_h():
    h = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    h.color(pen,al)
    h.speed()
    h.up()
    h.setposition(initial_x,initial_y)
    h.forward(1030+2*mu)
    h.down()
    h.shape("turtle")
    h.left(90)
    h.forward(100)
    h.right(90)
    h.up()
    h.forward(100)
    h.right(90)
    h.down()
    h.forward(100)
    h.up()
    h.backward(50)
    h.down()
    h.right(90)
    h.forward(100)
    h.hideturtle()

def write_i():
    i = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    i.color(pen,al)
    i.up()
    i.setposition(initial_x,second_row_y)
    i.down()
    i.shape("turtle")
    i.forward(100)
    i.up()
    i.left(90)
    i.forward(100)
    i.down()
    i.left(90)
    i.forward(100)
    i.backward(50)
    i.left(90)
    i.forward(100)
    i.hideturtle()

def write_j():
    j=turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    j.color(pen,al)
    j.speed(9)
    j.up()
    j.setposition(initial_x,second_row_y)
    j.forward(180)
    j.left(90)
    j.forward(100)
    j.down()
    j.shape("turtle")
    j.right(90)
    j.forward(100)
    j.backward(50)
    j.right(90)
    j.forward(60)
    j.circle(-40,180)
    j.hideturtle()
    
def write_k():
    k = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    k.color(pen,al)
    k.up()
    k.setposition(initial_x,second_row_y)
    k.forward(305+mu)
    k.down()
    k.shape("turtle")
    k.left(90)
    k.forward(100)
    k.right(90)
    k.up()
    k.forward(50)
    k.down()
    k.right(135)
    k.forward(50*pow(2,0.5))
    k.left(90)
    k.forward(50*pow(2,0.5))
    k.hideturtle()


def write_l():
    l = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    l.color(pen,al)
    l.up()
    l.setposition(initial_x,second_row_y)
    l.forward(455+mu)
    l.down()
    l.shape("turtle")
    l.forward(70)
    l.backward(70)
    l.left(90)
    l.forward(100)
    l.hideturtle()

    
def write_m():
    m = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    m.color(pen,al)
    m.up()
    m.setposition(initial_x,second_row_y)
    m.forward(580+2*mu)
    m.down()
    m.shape("turtle")
    m.left(90)
    m.forward(100)
    m.right(135)
    m.forward(50*pow(2,0.5))
    m.left(90)
    m.forward(50*pow(2,0.5))
    m.right(135)
    m.forward(100)
    m.hideturtle()

def write_n():
    n = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    n.color(pen,al)
    n.up()
    n.setposition(initial_x,second_row_y)
    n.forward(730+2*mu)
    n.down()
    n.shape("turtle")
    n.left(90)
    n.forward(100)
    n.right(135)
    n.forward(100*pow(2,0.5))
    n.left(135)
    n.forward(100)
    n.hideturtle()
   
def write_o():
    o = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    o.color(pen,al)
    o.up()
    o.setposition(initial_x,second_row_y)
    o.forward(930+2*mu)
    o.down()
    o.shape("turtle")
    o.circle(50)
    o.hideturtle()

def write_p():
    p = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    p.color(pen,al)
    p.up()
    p.setposition(initial_x,second_row_y)
    p.forward(1030+2*mu)
    p.down()
    p.shape("turtle")
    p.left(90)
    p.forward(100)
    p.right(90)
    p.forward(25)
    p.circle(-25,180)
    p.forward(25)
    p.hideturtle()
    
def write_q():
    q = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    q.color(pen,al)
    q.up()
    q.setposition(initial_x,third_row_y)
    q.forward(50)
    q.down()
    q.shape("turtle")
    q.circle(50)
    q.left(90)
    q.up()
    q.forward(50)
    q.right(135)
    q.forward(20)
    q.down()
    q.forward(50)
    q.hideturtle()

def write_r():
    r = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    r.color(pen,al)
    r.up()
    r.setposition(initial_x,third_row_y)
    r.forward(180)
    r.down()
    r.shape("turtle")
    r.left(90)
    r.forward(100)
    r.right(90)
    r.forward(25)
    r.circle(-25,180)
    r.forward(25)
    r.left(135)
    r.forward(50*pow(2,0.5))
    r.hideturtle()

def write_s():
    s  = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    s.color(pen,al)
    s.up()
    s.setposition(initial_x,third_row_y)
    s.forward(330+mu)
    s.down()
    s.shape("turtle")
    s.circle(25,180)
    s.up()
    s.circle(25,90)
    s.down()
    s.circle(25,270)
    s.right(180)
    s.up()
    s.circle(25,90)
    s.down()
    s.circle(25,270)
    s.hideturtle()
    
def write_t():
    t = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    t.color(pen,al)
    t.up()
    t.setposition(initial_x,third_row_y)
    t.forward(455+mu)
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.down()
    t.shape("turtle")
    t.left(90)
    t.forward(100)
    t.backward(50)
    t.left(90)
    t.forward(100)
    t.hideturtle()    

def write_u():
    u=turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    u.color(pen,al)
    u.up()
    u.setposition(initial_x,third_row_y)
    u.forward(580+2*mu)
    u.shape("turtle")
    u.left(90)
    u.forward(100)
    u.right(90)
    u.forward(80)
    u.right(90)
    u.down()
    u.forward(60)
    u.circle(-40,90)
    u.circle(-40,90)
    u.forward(60)
    u.hideturtle()
    
def write_v():
    v = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    v.color(pen,al)
    v.up()
    v.setposition(initial_x,third_row_y)
    v.forward(730+2*mu)
    v.shape("turtle")
    v.left(90)
    v.forward(100)
    v.right(157.5)
    v.down()
    v.forward(75*pow(5,0.2))
    v.left(135)
    v.forward(75*pow(5,0.2))
    v.hideturtle()

def write_w():
    w = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    w.color(pen,al)
    w.up()
    w.setposition(initial_x,third_row_y)
    w.forward(880+2*mu)
    w.left(90)
    w.down()
    w.shape("turtle")
    w.forward(100)
    w.backward(100)
    w.right(45)
    w.forward(50*pow(2,0.5))
    w.right(90)
    w.forward(50*pow(2,0.5))
    w.left(135)
    w.forward(100)
    w.hideturtle()
    
def write_x():
    x=turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    x.color(pen,al)
    x.up()
    x.setposition(initial_x,third_row_y)
    x.forward(1030+2*mu)
    x.down()
    x.shape("turtle")
    x.left(45)
    x.forward(100*pow(2,0.5))
    x.up()
    x.right(135)
    x.forward(100)
    x.down()
    x.right(135)
    x.forward(100*pow(2,0.5))
    x.hideturtle()

def write_y():
    y = turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    y.color(pen,al)
    y.up()
    y.setposition(initial_x,fourth_row_y)
    y.left(90)
    y.forward(100)
    y.down()
    y.shape("turtle")
    y.right(135)
    y.forward(50*pow(2,0.5))
    y.right(45)
    y.forward(50)
    y.backward(50)
    y.left(135)
    y.forward(50*pow(2,0.5))
    y.hideturtle()
    
def write_z():
    z= turtle.Turtle()
    pen = random.choice(colors)
    al = random.choice(colors)
    z.color(pen,al)
    z.up()
    z.setposition(initial_x,fourth_row_y)
    z.forward(180)
    z.shape("turtle")
    z.left(90)
    z.forward(100)
    z.right(90)
    z.down()
    z.forward(100)
    z.right(135)
    z.forward(100*pow(2,0.5))
    z.left(135)
    z.forward(100)
    z.hideturtle()

write_a()
write_b()
write_c()
write_d()
write_e()
write_f()
write_g()
write_h()
write_i()
write_j()
write_k()
write_l()
write_m()
write_n()
write_o()
write_p()
write_q()
write_r()
write_s()
write_t()
write_u()
write_v()
write_w()
write_x()
write_y()
write_z()
